# Generated by Django 6.1.1 on 2026-09-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_email_order_payment_method_order_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('damaged', 'Damaged Product'), ('wrong_product', 'Wrong Product'), ('quantity_issue', 'Quantity Issue'), ('quality_issue', 'Quality Issue'), ('not_received', 'Product Not Received'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('seller_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('seller_responded', 'Seller Responded'), ('under_review', 'Under Admin Review'), ('refund_approved', 'Refund Approved'), ('seller_favored', 'Resolved in Seller Favor'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('admin_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
