# Generated by Django 6.1.1 on 2026-09-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
        ('orders', '0003_order_email_order_payment_method_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_source', to='orders.order'),
        ),
    ]
