# Generated by Django 6.1.1 on 2026-09-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank / Card')], default='bkash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
    ]
